In [17]:
import numpy as np
from w1_unittest import *

ModuleNotFoundError: No module named 'w1_unittest'

In [ ]:
A = np.array([
            [-1,3],
            [3,2]
            ], dtype=np.dtype(float))

b = np.array([7,1],dtype=np.dtype(float))

print(A)
print(b)

print(A.shape)
print(b.shape)

x = np.linalg.solve(A,b)
print("find x1 and x2")
print(x)

print("find the determinant of A")
d = np.linalg.det(A)
print(f"{d:.2f}")

print("reshaping b from (2,) to (2,1)")
b = b.reshape(2,1)
print(b)

stacked_eq = np.hstack((A,b))
print("stacked equation") 
print(stacked_eq) 

plot_lines(stacked_eq)


[[-1.  3.]
 [ 3.  2.]]
[7. 1.]
(2, 2)
(2,)
find x1 and x2
[-1.  2.]
find the determinant of A
-11.00
reshaping b from (2,) to (2,1)
[[7.]
 [1.]]
stacked equation
[[-1.  3.  7.]
 [ 3.  2.  1.]]


NameError: name 'plot_lines' is not defined