Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [1]:
import numpy as np

arr1 = np.array(42)
arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)


0
1
2
3


Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [2]:
print(arr2[0])

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

1
7


Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [3]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 1])

2nd element on 1st row:  7


Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [4]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr.ndim)
print(arr[0,0,1])

3
2


Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:6])

print(arr[2:7:2])

[2 3 4 5 6]
[3 5 7]


Slicing 2-D Arrays

In [6]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

  Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:`b

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr2 = np.array(["banana","cherry","apple","strawberry"])

print(arr2.dtype)


int64
<U10


Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [8]:
arr = np.array([1, 2, 3, 4], dtype='str')

print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


In [9]:
arr = np.array([1, 2, 3, 4], dtype='int')

print(arr)
print(arr.dtype)

[1 2 3 4]
int64


In [10]:
arr = np.array([1, 2, 3, 4], dtype='bool')

print(arr)
print(arr.dtype)

[ True  True  True  True]
bool


In [11]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [12]:
arr = np.array(['a', '2', '3'], dtype='int')
print(arr.dtype)

ValueError: invalid literal for int() with base 10: 'a'

Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [ ]:
arr = np.array([1.1,2.2,3.3,4.4])
new_arr = arr.astype('int')
print(arr)
print(new_arr)

[1.1 2.2 3.3 4.4]
[1 2 3 4]


In [ ]:
arr = np.array([1, 0, 3, 0])
new_arr = arr.astype('bool')
print(arr)
print(new_arr)

[1 0 3 0]
[ True False  True False]


The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
x[0] = 99
print(x)
print(arr)

[99  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr = np.array([9,8,7,6])
x = arr.view()
print(arr)
x[0] = 1
print(x)
print(arr)

[9 8 7 6]
[1 8 7 6]
[1 8 7 6]


Shape of an Array
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [ ]:
array = np.array([[1,2,3],[5,5,6]])
print(array.shape)

(2, 3)


Another way to implement an array is using np.arange(). This function will return an array of evenly spaced values within a given interval. To learn more about the arguments that this function takes, there is a powerful feature in Jupyter Notebook that allows you to access the documentation of any function by simply pressing shift+tab on your keyboard when clicking on the function. Give it a try for the built-in documentation of np.arange().

In [ ]:
a = np.arange(20)
print(a)

b = np.arange(0, 20, 4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ 0  4  8 12 16]


What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice, you have 3 parameters that a function must take. One paremeter is the starting number, in this case 0, the final number 100 and the number of elements in the array, in this case, 5. NumPy has a function that allows you to do specifically this by using np.linspace()

In [33]:
lin_space_arr = np.linspace(0, 21, 3)
print(lin_space_arr)

lin_spaced_array= np.linspace(0,20,5,dtype=int)
print(lin_spaced_array)

[ 0.  10.5 21. ]
[ 0  5 10 15 20]


One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:

np.ones() - Returns a new array setting values to one.
np.zeros() - Returns a new array setting values to zero.
np.empty() - Returns a new uninitialized array.
np.random.rand() - Returns a new array with values chosen at random.

In [39]:
ones_array = np.ones(3)
print(ones_array)

zeros_array = np.zeros(4)
print(zeros_array)

empty_array = np.empty(5)
print(empty_array)

random_val = np.random.rand(4)
print(random_val)

[1. 1. 1.]
[0. 0. 0. 0.]
[0.0e+000 2.5e-323 4.9e-323 7.4e-323 9.9e-323]
[0.12353204 0.31606163 0.01493607 0.83230072]
