The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
x[0] = 99
print(x)
print(arr)

[99  2  3  4  5]
[1 2 3 4 5]


In [9]:
arr = np.array([9,8,7,6])
x = arr.view()
print(arr)
x[0] = 1
print(x)
print(arr)

[9 8 7 6]
[1 8 7 6]
[1 8 7 6]


Shape of an Array
The shape of an array is the number of elements in each dimension.

Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [13]:
array = np.array([[1,2,3],[5,5,6]])
print(array.shape)

(2, 3)
