Array math operations
In this section, you will see that NumPy allows you to quickly perform elementwise addition, substraction, multiplication and division for both 1-D and multidimensional arrays. The operations are performed using the math symbol for each '+', '-' and '*'. Recall that addition of Python lists works completely differently as it would append the lists, thus making a longer list, in addition, subtraction and multiplication of Python lists do not work.

In [6]:
import numpy as np

In [8]:
arr1 = np.array([2,3,4,5])
arr2 = np.array([3,4,5,6])

sum = arr1 + arr2
print(sum)

sub = arr1 - arr2
print(sub)

mul = arr1 * arr2
print(mul)


[ 5  7  9 11]
[-1 -1 -1 -1]
[ 6 12 20 30]
